image: ubuntu:22.04

tasks:
  - name: Setup Ashoka Environment
    init: |
      sudo apt-get update
      sudo apt-get install -y curl git python3 python3-pip netcat
      # Install GitHub CLI
      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
      sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      sudo apt-get update
      sudo apt-get install -y gh
      # Clone the repo
      git clone https://github.com/smart-social-contracts/ashoka.git /workspace/ashoka
      cd /workspace/ashoka
      # Install dependencies
      pip3 install -r requirements.txt
      # Install Ollama
      curl -fsSL https://ollama.com/install.sh | sh
    command: |
      echo "Starting Ashoka AI Governor environment..."
      # Start Ollama in the background
      ollama serve &
      echo "Waiting for Ollama to become available..."
      while ! nc -z localhost 11434; do
        sleep 1
      done
      echo "Ollama is up and running at http://localhost:11434"
      # Pull the llama3 model
      echo "Pulling llama3 model..."
      ollama pull llama3

ports:
  - port: 11434
    onOpen: ignore
    visibility: public

github:
  prebuilds:
    master: true
    branches: true
