version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5

  ashoka:
    build: .
    ports:
      - "5000:5000"
      - "11434:11434"
      - "5050:5050"
    depends_on:
      chromadb:
        condition: service_healthy
    environment:
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
    volumes:
      - ollama_data:/workspace/ollama

volumes:
  chromadb_data:
  ollama_data:
