name: Branch Pod Test

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push to Docker Hub"]
    types:
      - completed
    branches:
      - develop
      - staging
      - feature/*
      - fix/*
      - hotfix/*
  pull_request:
    branches:
      - main

jobs:
  test-branch-pod:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' }}
    env:
      RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
      BOOTUP_TIMEOUT_SEC: 600
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests runpod

      - name: Get pod URL and test Flask server
        run: |
          ./pod_manager.py branch restart --deploy-new-if-needed --verbose

          POD_URL=$(./pod_manager.py branch status --verbose 2>&1 | grep "Server Host:" | awk '{print "https://" $3}' || echo "")
          if [ -z "$POD_URL" ]; then
            echo "❌ Could not determine pod URL"
            exit 1
          fi
          echo "🔍 Testing pod at: $POD_URL"
          
          ./scripts/health_check.sh $BOOTUP_TIMEOUT_SEC "$POD_URL"
