name: Branch Pod Test

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - staging
      - feature/*
      - fix/*
      - hotfix/*
  pull_request:
    branches:
      - main

jobs:
  test-branch-pod:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Set RunPod API key
        run: echo "RUNPOD_API_KEY=${{ secrets.RUNPOD_API_KEY }}" >> $GITHUB_ENV

      - name: Start branch pod
        run: ./pod_manager.py branch start --verbose

      - name: Test Flask server
        run: |
          source ./env
          sleep 30
          curl -f --max-time 10 "https://$SERVER_HOST_BRANCH/health" || curl -f "https://$SERVER_HOST_BRANCH/"

      - name: Stop branch pod
        if: always()
        run: ./pod_manager.py branch stop
