name: Build and push to Docker Hub (plain docker)

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub using token
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u smartsocialcontracts --password-stdin

      - name: Build Docker image
        run: docker build -t smartsocialcontracts/ashoka:latest .

      - name: Push Docker image
        run: docker push smartsocialcontracts/ashoka:latest
