name: Integration Test

on:
  workflow_run:
    workflows: ["Branch Pod Test"]
    types:
      - completed

jobs:
  integration-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytest sentence-transformers scikit-learn numpy
        
    - name: Wait for pod to be ready
      run: |
        echo "Waiting for pod to be ready..."
        sleep 30
        
    - name: Get pod URL
      run: |
        python pod_manager.py branch status --verbose > pod_status.txt
        cat pod_status.txt
        POD_URL=$(grep -o 'https://[^[:space:]]*' pod_status.txt | head -1)
        echo "POD_URL=$POD_URL" >> $GITHUB_ENV
        echo "Pod URL: $POD_URL"
        
    - name: Run integration tests
      env:
        ASHOKA_API_URL: ${{ env.POD_URL }}
      run: |
        python -m pytest tests/test_integration_ask_endpoint.py -v --tb=short
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: integration-test-results
        path: |
          pytest.log
          test-results.xml
