name: Main Pod Test

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push to Docker Hub"]
    types:
      - completed
    branches:
      - main

jobs:
  test-main-pod:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    env:
      RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
      BOOTUP_TIMEOUT_SEC: 600

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests runpod

      - name: Run remote CI tests
        run: |
          ./pod_manager.py main restart --deploy-new-if-needed --verbose
          source <(./pod_manager.py main status)
          ./scripts/health_check.sh $BOOTUP_TIMEOUT_SEC "$POD_URL"
          ./scripts/run_remote_ci_tests.py $POD_URL
