name: Main Pod Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-main-pod:
    runs-on: ubuntu-latest
    env:
      RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
      TIMEOUT_SECS: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests runpod

      - name: Get pod URL and test Flask server
        run: |
          ./pod_manager.py main restart --deploy-new-if-needed --verbose

          POD_URL=$(./pod_manager.py main status --verbose 2>&1 | grep "Server Host:" | awk '{print "https://" $3}' || echo "")
          if [ -z "$POD_URL" ]; then
            echo "❌ Could not determine pod URL"
            exit 1
          fi
          echo "🔍 Testing pod at: $POD_URL"
          
          sleep $TIMEOUT_SECS
          
          curl -f --max-time 15 "$POD_URL/health" || curl -f --max-time 15 "$POD_URL/"
